import { Match, Team, UserProfile, Forecast, League } from './types';

export const TEAMS: Record<string, Team> = {
  'ALG': { id: 'ALG', name: 'Argelia', flag: '🇩🇿', group: 'Grupo J' },
  'ARG': { id: 'ARG', name: 'Argentina', flag: '🇦🇷', group: 'Grupo J' },
  'AUS': { id: 'AUS', name: 'Australia', flag: '🇦🇺', group: 'Grupo D' },
  'AUT': { id: 'AUT', name: 'Austria', flag: '🇦🇹', group: 'Grupo J' },
  'BEL': { id: 'BEL', name: 'Bélgica', flag: '🇧🇪', group: 'Grupo G' },
  'BIH': { id: 'BIH', name: 'Bosnia y H.', flag: '🇧🇦', group: 'Grupo B' },
  'BRA': { id: 'BRA', name: 'Brasil', flag: '🇧🇷', group: 'Grupo C' },
  'CAN': { id: 'CAN', name: 'Canadá', flag: '🇨🇦', group: 'Grupo B' },
  'CIV': { id: 'CIV', name: 'Costa de Marfil', flag: '🇨🇮', group: 'Grupo E' },
  'COD': { id: 'COD', name: 'R. D. Congo', flag: '🇨🇩', group: 'Grupo K' },
  'COL': { id: 'COL', name: 'Colombia', flag: '🇨🇴', group: 'Grupo K' },
  'CPV': { id: 'CPV', name: 'Cabo Verde', flag: '🇨🇻', group: 'Grupo H' },
  'CRO': { id: 'CRO', name: 'Croacia', flag: '🇭🇷', group: 'Grupo L' },
  'CUW': { id: 'CUW', name: 'Curazao', flag: '🇨🇼', group: 'Grupo E' },
  'CZE': { id: 'CZE', name: 'República Checa', flag: '🇨🇿', group: 'Grupo A' },
  'ECU': { id: 'ECU', name: 'Ecuador', flag: '🇪🇨', group: 'Grupo E' },
  'EGY': { id: 'EGY', name: 'Egipto', flag: '🇪🇬', group: 'Grupo G' },
  'ENG': { id: 'ENG', name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'Grupo L' },
  'ESP': { id: 'ESP', name: 'España', flag: '🇪🇸', group: 'Grupo H' },
  'FRA': { id: 'FRA', name: 'Francia', flag: '🇫🇷', group: 'Grupo I' },
  'GER': { id: 'GER', name: 'Alemania', flag: '🇩🇪', group: 'Grupo E' },
  'GHA': { id: 'GHA', name: 'Ghana', flag: '🇬🇭', group: 'Grupo L' },
  'HAI': { id: 'HAI', name: 'Haití', flag: '🇭🇹', group: 'Grupo C' },
  'IRN': { id: 'IRN', name: 'Irán', flag: '🇮🇷', group: 'Grupo G' },
  'IRQ': { id: 'IRQ', name: 'Irak', flag: '🇮🇶', group: 'Grupo I' },
  'JOR': { id: 'JOR', name: 'Jordania', flag: '🇯🇴', group: 'Grupo J' },
  'JPN': { id: 'JPN', name: 'Japón', flag: '🇯🇵', group: 'Grupo F' },
  'KOR': { id: 'KOR', name: 'Corea del Sur', flag: '🇰🇷', group: 'Grupo A' },
  'KSA': { id: 'KSA', name: 'Arabia Saudita', flag: '🇸🇦', group: 'Grupo H' },
  'MAR': { id: 'MAR', name: 'Marruecos', flag: '🇲🇦', group: 'Grupo C' },
  'MEX': { id: 'MEX', name: 'México', flag: '🇲🇽', group: 'Grupo A' },
  'NED': { id: 'NED', name: 'Países Bajos', flag: '🇳🇱', group: 'Grupo F' },
  'NOR': { id: 'NOR', name: 'Noruega', flag: '🇳🇴', group: 'Grupo I' },
  'NZL': { id: 'NZL', name: 'Nueva Zelanda', flag: '🇳🇿', group: 'Grupo G' },
  'PAN': { id: 'PAN', name: 'Panamá', flag: '🇵🇦', group: 'Grupo L' },
  'PAR': { id: 'PAR', name: 'Paraguay', flag: '🇵🇾', group: 'Grupo D' },
  'POR': { id: 'POR', name: 'Portugal', flag: '🇵🇹', group: 'Grupo K' },
  'QAT': { id: 'QAT', name: 'Catar', flag: '🇶🇦', group: 'Grupo B' },
  'RSA': { id: 'RSA', name: 'Sudáfrica', flag: '🇿🇦', group: 'Grupo A' },
  'SCO': { id: 'SCO', name: 'Escocia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'Grupo C' },
  'SEN': { id: 'SEN', name: 'Senegal', flag: '🇸🇳', group: 'Grupo I' },
  'SUI': { id: 'SUI', name: 'Suiza', flag: '🇨🇭', group: 'Grupo B' },
  'SWE': { id: 'SWE', name: 'Suecia', flag: '🇸🇪', group: 'Grupo F' },
  'TUN': { id: 'TUN', name: 'Túnez', flag: '🇹🇳', group: 'Grupo F' },
  'TUR': { id: 'TUR', name: 'Turquía', flag: '🇹🇷', group: 'Grupo D' },
  'URU': { id: 'URU', name: 'Uruguay', flag: '🇺🇾', group: 'Grupo H' },
  'USA': { id: 'USA', name: 'EE. UU.', flag: '🇺🇸', group: 'Grupo D' },
  'UZB': { id: 'UZB', name: 'Uzbekistán', flag: '🇺🇿', group: 'Grupo K' },
  '1A': { id: '1A', name: '1A', flag: '🏳️', group: 'Eliminatoria' },
  '1B': { id: '1B', name: '1B', flag: '🏳️', group: 'Eliminatoria' },
  '1C': { id: '1C', name: '1C', flag: '🏳️', group: 'Eliminatoria' },
  '1D': { id: '1D', name: '1D', flag: '🏳️', group: 'Eliminatoria' },
  '1E': { id: '1E', name: '1E', flag: '🏳️', group: 'Eliminatoria' },
  '1F': { id: '1F', name: '1F', flag: '🏳️', group: 'Eliminatoria' },
  '1G': { id: '1G', name: '1G', flag: '🏳️', group: 'Eliminatoria' },
  '1H': { id: '1H', name: '1H', flag: '🏳️', group: 'Eliminatoria' },
  '1I': { id: '1I', name: '1I', flag: '🏳️', group: 'Eliminatoria' },
  '1J': { id: '1J', name: '1J', flag: '🏳️', group: 'Eliminatoria' },
  '1K': { id: '1K', name: '1K', flag: '🏳️', group: 'Eliminatoria' },
  '1L': { id: '1L', name: '1L', flag: '🏳️', group: 'Eliminatoria' },
  '2A': { id: '2A', name: '2A', flag: '🏳️', group: 'Eliminatoria' },
  '2B': { id: '2B', name: '2B', flag: '🏳️', group: 'Eliminatoria' },
  '2C': { id: '2C', name: '2C', flag: '🏳️', group: 'Eliminatoria' },
  '2D': { id: '2D', name: '2D', flag: '🏳️', group: 'Eliminatoria' },
  '2E': { id: '2E', name: '2E', flag: '🏳️', group: 'Eliminatoria' },
  '2F': { id: '2F', name: '2F', flag: '🏳️', group: 'Eliminatoria' },
  '2G': { id: '2G', name: '2G', flag: '🏳️', group: 'Eliminatoria' },
  '2H': { id: '2H', name: '2H', flag: '🏳️', group: 'Eliminatoria' },
  '2I': { id: '2I', name: '2I', flag: '🏳️', group: 'Eliminatoria' },
  '2J': { id: '2J', name: '2J', flag: '🏳️', group: 'Eliminatoria' },
  '2K': { id: '2K', name: '2K', flag: '🏳️', group: 'Eliminatoria' },
  '2L': { id: '2L', name: '2L', flag: '🏳️', group: 'Eliminatoria' },
  '3ABCDF': { id: '3ABCDF', name: '3ABCDF', flag: '🏳️', group: 'Eliminatoria' },
  '3AEHIJ': { id: '3AEHIJ', name: '3AEHIJ', flag: '🏳️', group: 'Eliminatoria' },
  '3BEFIJ': { id: '3BEFIJ', name: '3BEFIJ', flag: '🏳️', group: 'Eliminatoria' },
  '3CDFGH': { id: '3CDFGH', name: '3CDFGH', flag: '🏳️', group: 'Eliminatoria' },
  '3CEFHI': { id: '3CEFHI', name: '3CEFHI', flag: '🏳️', group: 'Eliminatoria' },
  '3DEIJL': { id: '3DEIJL', name: '3DEIJL', flag: '🏳️', group: 'Eliminatoria' },
  '3EFGIJ': { id: '3EFGIJ', name: '3EFGIJ', flag: '🏳️', group: 'Eliminatoria' },
  '3EHIJK': { id: '3EHIJK', name: '3EHIJK', flag: '🏳️', group: 'Eliminatoria' },
  'TBD_TBA': { id: 'TBD_TBA', name: 'Por definir', flag: '🏳️', group: 'Eliminatoria' }
};

export const INITIAL_MATCHES: Match[] = [
  { id: 'M_1', homeTeam: TEAMS['MEX'], awayTeam: TEAMS['RSA'], dateTime: '2026-06-11T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_2', homeTeam: TEAMS['KOR'], awayTeam: TEAMS['CZE'], dateTime: '2026-06-12T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_3', homeTeam: TEAMS['CAN'], awayTeam: TEAMS['BIH'], dateTime: '2026-06-12T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_4', homeTeam: TEAMS['USA'], awayTeam: TEAMS['PAR'], dateTime: '2026-06-13T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_5', homeTeam: TEAMS['QAT'], awayTeam: TEAMS['SUI'], dateTime: '2026-06-13T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_6', homeTeam: TEAMS['BRA'], awayTeam: TEAMS['MAR'], dateTime: '2026-06-13T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_7', homeTeam: TEAMS['HAI'], awayTeam: TEAMS['SCO'], dateTime: '2026-06-14T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_8', homeTeam: TEAMS['AUS'], awayTeam: TEAMS['TUR'], dateTime: '2026-06-14T04:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_9', homeTeam: TEAMS['GER'], awayTeam: TEAMS['CUW'], dateTime: '2026-06-14T17:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_10', homeTeam: TEAMS['NED'], awayTeam: TEAMS['JPN'], dateTime: '2026-06-14T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_11', homeTeam: TEAMS['CIV'], awayTeam: TEAMS['ECU'], dateTime: '2026-06-14T23:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_12', homeTeam: TEAMS['SWE'], awayTeam: TEAMS['TUN'], dateTime: '2026-06-15T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_13', homeTeam: TEAMS['ESP'], awayTeam: TEAMS['CPV'], dateTime: '2026-06-15T16:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_14', homeTeam: TEAMS['BEL'], awayTeam: TEAMS['EGY'], dateTime: '2026-06-15T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_15', homeTeam: TEAMS['KSA'], awayTeam: TEAMS['URU'], dateTime: '2026-06-15T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_16', homeTeam: TEAMS['IRN'], awayTeam: TEAMS['NZL'], dateTime: '2026-06-16T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_17', homeTeam: TEAMS['FRA'], awayTeam: TEAMS['SEN'], dateTime: '2026-06-16T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_18', homeTeam: TEAMS['IRQ'], awayTeam: TEAMS['NOR'], dateTime: '2026-06-16T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_19', homeTeam: TEAMS['ARG'], awayTeam: TEAMS['ALG'], dateTime: '2026-06-17T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_20', homeTeam: TEAMS['AUT'], awayTeam: TEAMS['JOR'], dateTime: '2026-06-17T04:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_21', homeTeam: TEAMS['POR'], awayTeam: TEAMS['COD'], dateTime: '2026-06-17T17:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_22', homeTeam: TEAMS['ENG'], awayTeam: TEAMS['CRO'], dateTime: '2026-06-17T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_23', homeTeam: TEAMS['GHA'], awayTeam: TEAMS['PAN'], dateTime: '2026-06-17T23:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_24', homeTeam: TEAMS['UZB'], awayTeam: TEAMS['COL'], dateTime: '2026-06-18T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_25', homeTeam: TEAMS['CZE'], awayTeam: TEAMS['RSA'], dateTime: '2026-06-18T16:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_26', homeTeam: TEAMS['SUI'], awayTeam: TEAMS['BIH'], dateTime: '2026-06-18T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_27', homeTeam: TEAMS['CAN'], awayTeam: TEAMS['QAT'], dateTime: '2026-06-18T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_28', homeTeam: TEAMS['MEX'], awayTeam: TEAMS['KOR'], dateTime: '2026-06-19T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_29', homeTeam: TEAMS['USA'], awayTeam: TEAMS['AUS'], dateTime: '2026-06-19T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_30', homeTeam: TEAMS['SCO'], awayTeam: TEAMS['MAR'], dateTime: '2026-06-19T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_31', homeTeam: TEAMS['BRA'], awayTeam: TEAMS['HAI'], dateTime: '2026-06-20T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_32', homeTeam: TEAMS['TUR'], awayTeam: TEAMS['PAR'], dateTime: '2026-06-20T04:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_33', homeTeam: TEAMS['NED'], awayTeam: TEAMS['SWE'], dateTime: '2026-06-20T17:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_34', homeTeam: TEAMS['GER'], awayTeam: TEAMS['CIV'], dateTime: '2026-06-20T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_35', homeTeam: TEAMS['ECU'], awayTeam: TEAMS['CUW'], dateTime: '2026-06-21T00:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_36', homeTeam: TEAMS['TUN'], awayTeam: TEAMS['JPN'], dateTime: '2026-06-21T04:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_37', homeTeam: TEAMS['ESP'], awayTeam: TEAMS['KSA'], dateTime: '2026-06-21T16:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_38', homeTeam: TEAMS['BEL'], awayTeam: TEAMS['IRN'], dateTime: '2026-06-21T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_39', homeTeam: TEAMS['URU'], awayTeam: TEAMS['CPV'], dateTime: '2026-06-21T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_40', homeTeam: TEAMS['NZL'], awayTeam: TEAMS['EGY'], dateTime: '2026-06-22T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_41', homeTeam: TEAMS['ARG'], awayTeam: TEAMS['AUT'], dateTime: '2026-06-22T17:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_42', homeTeam: TEAMS['FRA'], awayTeam: TEAMS['IRQ'], dateTime: '2026-06-22T21:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_43', homeTeam: TEAMS['NOR'], awayTeam: TEAMS['SEN'], dateTime: '2026-06-23T00:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_44', homeTeam: TEAMS['JOR'], awayTeam: TEAMS['ALG'], dateTime: '2026-06-23T03:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_45', homeTeam: TEAMS['POR'], awayTeam: TEAMS['UZB'], dateTime: '2026-06-23T17:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_46', homeTeam: TEAMS['ENG'], awayTeam: TEAMS['GHA'], dateTime: '2026-06-23T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_47', homeTeam: TEAMS['PAN'], awayTeam: TEAMS['CRO'], dateTime: '2026-06-23T23:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_48', homeTeam: TEAMS['COL'], awayTeam: TEAMS['COD'], dateTime: '2026-06-24T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_49', homeTeam: TEAMS['SUI'], awayTeam: TEAMS['CAN'], dateTime: '2026-06-24T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_50', homeTeam: TEAMS['BIH'], awayTeam: TEAMS['QAT'], dateTime: '2026-06-24T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_51', homeTeam: TEAMS['SCO'], awayTeam: TEAMS['BRA'], dateTime: '2026-06-24T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_52', homeTeam: TEAMS['MAR'], awayTeam: TEAMS['HAI'], dateTime: '2026-06-24T22:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_53', homeTeam: TEAMS['CZE'], awayTeam: TEAMS['MEX'], dateTime: '2026-06-25T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_54', homeTeam: TEAMS['RSA'], awayTeam: TEAMS['KOR'], dateTime: '2026-06-25T01:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_55', homeTeam: TEAMS['CUW'], awayTeam: TEAMS['CIV'], dateTime: '2026-06-25T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_56', homeTeam: TEAMS['ECU'], awayTeam: TEAMS['GER'], dateTime: '2026-06-25T20:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_57', homeTeam: TEAMS['JPN'], awayTeam: TEAMS['SWE'], dateTime: '2026-06-25T23:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_58', homeTeam: TEAMS['TUN'], awayTeam: TEAMS['NED'], dateTime: '2026-06-25T23:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_59', homeTeam: TEAMS['TUR'], awayTeam: TEAMS['USA'], dateTime: '2026-06-26T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_60', homeTeam: TEAMS['PAR'], awayTeam: TEAMS['AUS'], dateTime: '2026-06-26T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_61', homeTeam: TEAMS['NOR'], awayTeam: TEAMS['FRA'], dateTime: '2026-06-26T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_62', homeTeam: TEAMS['SEN'], awayTeam: TEAMS['IRQ'], dateTime: '2026-06-26T19:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_63', homeTeam: TEAMS['CPV'], awayTeam: TEAMS['KSA'], dateTime: '2026-06-27T00:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_64', homeTeam: TEAMS['URU'], awayTeam: TEAMS['ESP'], dateTime: '2026-06-27T00:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_65', homeTeam: TEAMS['EGY'], awayTeam: TEAMS['IRN'], dateTime: '2026-06-27T03:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_66', homeTeam: TEAMS['NZL'], awayTeam: TEAMS['BEL'], dateTime: '2026-06-27T03:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_67', homeTeam: TEAMS['PAN'], awayTeam: TEAMS['ENG'], dateTime: '2026-06-27T21:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_68', homeTeam: TEAMS['CRO'], awayTeam: TEAMS['GHA'], dateTime: '2026-06-27T21:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_69', homeTeam: TEAMS['COL'], awayTeam: TEAMS['POR'], dateTime: '2026-06-27T23:30:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_70', homeTeam: TEAMS['COD'], awayTeam: TEAMS['UZB'], dateTime: '2026-06-27T23:30:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_71', homeTeam: TEAMS['ALG'], awayTeam: TEAMS['AUT'], dateTime: '2026-06-28T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_72', homeTeam: TEAMS['JOR'], awayTeam: TEAMS['ARG'], dateTime: '2026-06-28T02:00:00Z', phase: 'group', status: 'scheduled' },
  { id: 'M_73', homeTeam: TEAMS['2A'], awayTeam: TEAMS['2B'], dateTime: '2026-06-28T19:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_74', homeTeam: TEAMS['1C'], awayTeam: TEAMS['2F'], dateTime: '2026-06-29T17:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_75', homeTeam: TEAMS['1E'], awayTeam: TEAMS['3ABCDF'], dateTime: '2026-06-29T20:30:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_76', homeTeam: TEAMS['1F'], awayTeam: TEAMS['2C'], dateTime: '2026-06-30T01:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_77', homeTeam: TEAMS['2E'], awayTeam: TEAMS['2I'], dateTime: '2026-06-30T17:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_78', homeTeam: TEAMS['1I'], awayTeam: TEAMS['3CDFGH'], dateTime: '2026-06-30T21:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_79', homeTeam: TEAMS['1A'], awayTeam: TEAMS['3CEFHI'], dateTime: '2026-07-01T01:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_80', homeTeam: TEAMS['1L'], awayTeam: TEAMS['3EHIJK'], dateTime: '2026-07-01T16:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_81', homeTeam: TEAMS['1G'], awayTeam: TEAMS['3AEHIJ'], dateTime: '2026-07-01T20:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_82', homeTeam: TEAMS['1D'], awayTeam: TEAMS['3BEFIJ'], dateTime: '2026-07-02T00:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_83', homeTeam: TEAMS['1H'], awayTeam: TEAMS['2J'], dateTime: '2026-07-02T19:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_84', homeTeam: TEAMS['2K'], awayTeam: TEAMS['2L'], dateTime: '2026-07-02T23:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_85', homeTeam: TEAMS['1B'], awayTeam: TEAMS['3EFGIJ'], dateTime: '2026-07-03T03:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_86', homeTeam: TEAMS['2D'], awayTeam: TEAMS['2G'], dateTime: '2026-07-03T18:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_87', homeTeam: TEAMS['1J'], awayTeam: TEAMS['2H'], dateTime: '2026-07-03T22:00:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_88', homeTeam: TEAMS['1K'], awayTeam: TEAMS['3DEIJL'], dateTime: '2026-07-04T01:30:00Z', phase: 'dieciseisavos', status: 'scheduled' },
  { id: 'M_89', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-04T17:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_90', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-04T21:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_91', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-05T20:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_92', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-06T00:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_93', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-06T19:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_94', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-07T00:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_95', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-07T16:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_96', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-07T20:00:00Z', phase: 'octavos', status: 'scheduled' },
  { id: 'M_97', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-09T20:00:00Z', phase: 'cuartos', status: 'scheduled' },
  { id: 'M_98', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-10T19:00:00Z', phase: 'cuartos', status: 'scheduled' },
  { id: 'M_99', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-11T21:00:00Z', phase: 'cuartos', status: 'scheduled' },
  { id: 'M_100', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-12T01:00:00Z', phase: 'cuartos', status: 'scheduled' },
  { id: 'M_101', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-14T19:00:00Z', phase: 'semifinal', status: 'scheduled' },
  { id: 'M_102', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-15T19:00:00Z', phase: 'semifinal', status: 'scheduled' },
  { id: 'M_103', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-18T21:00:00Z', phase: 'final', status: 'scheduled' },
  { id: 'M_104', homeTeam: TEAMS['TBD_TBA'], awayTeam: TEAMS['TBD_TBA'], dateTime: '2026-07-19T19:00:00Z', phase: 'final', status: 'scheduled' }
];

export const INITIAL_USERS: UserProfile[] = [
  { id: 'U1', name: 'Santiago (Tú)', avatar: '🦁', isAdmin: true },
  { id: 'U2', name: 'Laura Gómez', avatar: '🐱' },
  { id: 'U3', name: 'Andrés López', avatar: '🐼' },
  { id: 'U4', name: 'Camila Rivas', avatar: '🦊' }
];

export const INITIAL_LEAGUES: League[] = [
  {
    code: 'MUNDIAL2026',
    name: 'Grupo de la Oficina 💼',
    creatorId: 'U1',
    members: ['U1', 'U2', 'U3', 'U4']
  },
  {
    code: 'AMIGOS_FC',
    name: 'Amigos del Círculo ⚽',
    creatorId: 'U2',
    members: ['U1', 'U2', 'U3']
  }
];

export const INITIAL_FORECASTS: Forecast[] = [];
